#ifndef CFGPOSITIONLOOP_GLOBAL_H
#define CFGPOSITIONLOOP_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(CFGPOSITIONLOOP_LIBRARY)
#  define CFGPOSITIONLOOPSHARED_EXPORT Q_DECL_EXPORT
#else
#  define CFGPOSITIONLOOPSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // CFGPOSITIONLOOP_GLOBAL_H
