#ifndef ABSTRACTFUNCWIDGET_GLOBAL_H
#define ABSTRACTFUNCWIDGET_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(ABSTRACTFUNCWIDGET_LIBRARY)
#  define ABSTRACTFUNCWIDGETSHARED_EXPORT Q_DECL_EXPORT
#else
#  define ABSTRACTFUNCWIDGETSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // ABSTRACTFUNCWIDGET_GLOBAL_H
