#ifndef CFGDRIVERPOWER_GLOBAL_H
#define CFGDRIVERPOWER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(CFGDRIVERPOWER_LIBRARY)
#  define CFGDRIVERPOWERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define CFGDRIVERPOWERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // CFGDRIVERPOWER_GLOBAL_H
