#ifndef CFGSPEEDLOOP_GLOBAL_H
#define CFGSPEEDLOOP_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(CFGSPEEDLOOP_LIBRARY)
#  define CFGSPEEDLOOPSHARED_EXPORT Q_DECL_EXPORT
#else
#  define CFGSPEEDLOOPSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // CFGSPEEDLOOP_GLOBAL_H
