#ifndef DEVICESTATUS_GLOBAL_H
#define DEVICESTATUS_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(DEVICESTATUS_LIBRARY)
#  define DEVICESTATUSSHARED_EXPORT Q_DECL_EXPORT
#else
#  define DEVICESTATUSSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // DEVICESTATUS_GLOBAL_H
