#ifndef CFGMOVEPROFILE_GLOBAL_H
#define CFGMOVEPROFILE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(CFGMOVEPROFILE_LIBRARY)
#  define CFGMOVEPROFILESHARED_EXPORT Q_DECL_EXPORT
#else
#  define CFGMOVEPROFILESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // CFGMOVEPROFILE_GLOBAL_H
