#ifndef SERVOGENERALCMD_GLOBAL_H
#define SERVOGENERALCMD_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(SERVOGENERALCMD_LIBRARY)
#  define SERVOGENERALCMDSHARED_EXPORT Q_DECL_EXPORT
#else
#  define SERVOGENERALCMDSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // SERVOGENERALCMD_GLOBAL_H
